server:
  port: 8080

spring:

  application:
    name: eform-api
  
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./database/appDB
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true

  data:
    web:
      pageable:
        default-page-size: 10

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eform-sso.herokuapp.com/auth/realms/master

feign:
  client:
    config:
      default:
        loggerLevel: full

custom:
  sso:
    client-admin-id: admin-cli
    client-user-name: admin
    client-user-pass: admin